# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish

on:
  release:
    types: [created]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo chmod +x src/configure
      - run: mkdir temp
      - run: cd temp
      - run: tar --warning=no-file-changed --exclude='../temp' --exclude='../.git' --exclude='../.github' -czvf octave_zstd.tar.gz ../
      - run: gh release upload 1.0.3 octave_zstd.tar.gz --repo $GITHUB_REPOSITORY
