# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish

on:
  release:
    types: [created]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'octave_zstd'
      # uncomment this on demand
      - run: sudo chmod a+x octave_tar/src/configure
      # uncomment this on demand
      - run: sudo chmod -R a+x octave_tar/inst
      - run: tar --warning=no-file-changed --exclude='octave_zstd/.git' --exclude='octave_zstd/.github' -czvf octave_zstd.tar.gz octave_zstd
      - run: gh release upload 1.1.0 octave_zstd.tar.gz --repo $GITHUB_REPOSITORY
